//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: extract_frame.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef RATVIDEO_EXTRACT_FRAME_BASE_CLASSES_H
#define RATVIDEO_EXTRACT_FRAME_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class DlgExtractFrameBase : public wxDialog
{
protected:
    wxPanel* m_panel34;
    wxStaticText* m_staticText38;
    wxTextCtrl* m_textCtrlOutPath;
    wxStaticText* m_staticText6;
    wxTextCtrl* m_textCtrlFrom;
    wxStaticText* m_staticText20;
    wxTextCtrl* m_textCtrlTo;
    wxStdDialogButtonSizer* m_stdBtnSizer48;
    wxButton* m_button50;
    wxButton* m_button52;

protected:

public:
    wxStaticText* GetStaticText38() { return m_staticText38; }
    wxTextCtrl* GetTextCtrlOutPath() { return m_textCtrlOutPath; }
    wxStaticText* GetStaticText6() { return m_staticText6; }
    wxTextCtrl* GetTextCtrlFrom() { return m_textCtrlFrom; }
    wxStaticText* GetStaticText20() { return m_staticText20; }
    wxTextCtrl* GetTextCtrlTo() { return m_textCtrlTo; }
    wxPanel* GetPanel34() { return m_panel34; }
    DlgExtractFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Extract Frames"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,250), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgExtractFrameBase();
};

#endif
